FROM openjdk:8-jdk-alpine

# Add Maintainer Info
LABEL maintainer="M1050360@mindtree.com"

# Add a volume pointing to /tmp
VOLUME /tmp

# Make port 8080 available to the world outside this container
EXPOSE 8080

ARG JAR_FILE=build/libs/clients-0.1.jar

ADD ${JAR_FILE} corda-harvest-demo-farm-client.jar

ENTRYPOINT ["java","-jar","/corda-harvest-demo-farm-client.jar"]